//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defect_log
    {
        public int Round { get; set; }
        public Nullable<int> Defect_No { get; set; }
        public Nullable<int> Testcase_ID { get; set; }
        public string Scenario_Des { get; set; }
        public string Status { get; set; }
        public string Severity { get; set; }
        public string Priority { get; set; }
        public string Phase_Defect_Introduce { get; set; }
        public string Reported_by { get; set; }
        public Nullable<System.DateTime> Reported_date { get; set; }
        public string Developer_Name { get; set; }
        public string Developer_Comment { get; set; }
        public string Action_to_be_taken { get; set; }
        public string Resolved_by { get; set; }
        public Nullable<System.DateTime> Resolved_date { get; set; }
        public string Retest_by { get; set; }
        public Nullable<System.DateTime> Retest_date { get; set; }
        public string Remark { get; set; }
    }
}
