//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class items_in_factor_table
    {
        [Key]
        public int iif_id { get; set; }
        [Required]
        public string item { get; set; }
        public int fn_id { get; set; }
    
        public virtual factors_name_table factors_name_table { get; set; }
    }
}
