//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class test_case_table
    {
        public int test_case_id { get; set; }
        [Required]
        public string test_case_data { get; set; }
        [Required]
        public string expected_result { get; set; }
        [Required]
        public string test_round { get; set; }
        [Required]
        public string result { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime? date { get; set; }
        public string test_by { get; set; }
        [StringLength(255)]
        public string path_test_case { get; set; }
        [StringLength(255)]
        public string path_expected_result { get; set; }
        [StringLength(255)]
        public string factors2 { get; set; }
        public int module_id { get; set; }
        //Add New      
        public virtual list_module_name_table list_module_name_table { get; set; }
    }
}
